### ISSUE TITLE
tutorial breaks locally

### ISSUE THREAD

**Issue by koaning** [rohanshiva/Deta-FastAPI-JWT-Auth-Blog#2]
After setting up the project locally and installing everything I get this error upon running `unicorn main:app`. 

```
> uvicorn main:app
Traceback (most recent call last):
  File "/Users/vincent/Development/Deta-FastAPI-JWT-Auth-Blog/venv/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/Users/vincent/Development/Deta-FastAPI-JWT-Auth-Blog/venv/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/vincent/Development/Deta-FastAPI-JWT-Auth-Blog/venv/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/vincent/Development/Deta-FastAPI-JWT-Auth-Blog/venv/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/vincent/Development/Deta-FastAPI-JWT-Auth-Blog/venv/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/vincent/Development/Deta-FastAPI-JWT-Auth-Blog/venv/lib/python3.9/site-packages/uvicorn/main.py", line 362, in main
    run(**kwargs)
  File "/Users/vincent/Development/Deta-FastAPI-JWT-Auth-Blog/venv/lib/python3.9/site-packages/uvicorn/main.py", line 386, in run
    server.run()
  File "/Users/vincent/Development/Deta-FastAPI-JWT-Auth-Blog/venv/lib/python3.9/site-packages/uvicorn/server.py", line 49, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/vincent/Development/Deta-FastAPI-JWT-Auth-Blog/venv/lib/python3.9/site-packages/uvicorn/server.py", line 56, in serve
    config.load()
  File "/Users/vincent/Development/Deta-FastAPI-JWT-Auth-Blog/venv/lib/python3.9/site-packages/uvicorn/config.py", line 308, in load
    self.loaded_app = import_from_string(self.app)
  File "/Users/vincent/Development/Deta-FastAPI-JWT-Auth-Blog/venv/lib/python3.9/site-packages/uvicorn/importer.py", line 20, in import_from_string
    module = importlib.import_module(module_str)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "./main.py", line 8, in <module>
    deta = Deta()
  File "/Users/vincent/Development/Deta-FastAPI-JWT-Auth-Blog/venv/lib/python3.9/site-packages/deta/__init__.py", line 27, in __init__
    self.project_id = self.project_key.split("_")[0]
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by rohanshiva** [comment]
If you are running locally, you need to provide a project key for deta like this `deta = Deta(PROJECT_KEY)`
